### PR TITLE
New strings & error msgs. in hebrew

### PR DESCRIPTION
**Pull request by jocker-il**
Translation & invertion for new strings:

- sensor.day_time format
- sensor.day_time settings
- sensor.day_time show_day_number

**added** Hebrew strings to new English error strings:

- settings_badcall
- settings_whatsensor
- settings_whatsettings

I decided to leave the english strings and just add hebrew string after them to give the user the ability to post the error to the forum and get help from english speaking people. If i had replaced the english with hebrew text, the user would not be able to get help in english but rather just in hebrew or just from me since I have access to both...

### CODE REVIEW

**Comment by narc0tiq** [comment]
This is a trick I learned from working on https://github.com/CleverRaven/Cataclysm-DDA -- we use the [WIP] tag in the title to mark pull requests as incomplete, and remove the tag when it's ready (there's also [CR] for "comments requested", when a pull request is making a large change that should be discussed). I just changed the title here so I don't get tempted to merge the PR before it's ready.

**Comment by jocker-il** [comment]
I almost missed "settings.sensors_frame.title" :) - but I saw it just in time before to push when I was commenting on the changes I made for this commit...

 It seams to be a good thing that I record ( and review) all the changes and additions I make in the comment section of a commit

**Comment by narc0tiq** [comment]
Looking good, I think once I get this in, we're having an official 0.4.2.

**Comment by jocker-il** [comment]
yay - version 0.4.2 !

**Pull request merged**
